/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiClient } from '../lib/api-client';
export type PostUsuariosLoginBodyOne = {
  usuario: string;
  senha: string;
};

export type PostUsuariosLoginBodyTwo = {
  usuario: string;
  senha: string;
};

export type PostUsuariosLoginBodyThree = {
  usuario: string;
  senha: string;
};

export type GetUsuariosParams = {
pagina?: string | number;
limite?: string | number;
};

export type PostUsuariosBodyOne = {
  nome: string;
  email: string;
  usuario: string;
  senha: string;
  biografia?: string;
  foto?: string;
};

export type PostUsuariosBodyTwo = {
  nome: string;
  email: string;
  usuario: string;
  senha: string;
  biografia?: string;
  foto?: string;
};

export type PostUsuariosBodyThree = {
  nome: string;
  email: string;
  usuario: string;
  senha: string;
  biografia?: string;
  foto?: string;
};

export type PatchUsuariosByIdBodyOne = {
  nome: string;
  email: string;
  usuario: string;
  biografia?: string;
  foto?: string;
  senha?: string;
};

export type PatchUsuariosByIdBodyTwo = {
  nome: string;
  email: string;
  usuario: string;
  biografia?: string;
  foto?: string;
  senha?: string;
};

export type PatchUsuariosByIdBodyThree = {
  nome: string;
  email: string;
  usuario: string;
  biografia?: string;
  foto?: string;
  senha?: string;
};

export type getHealthResponse200 = {
  data: void
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  return apiClient<getHealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postUsuariosLoginResponse200 = {
  data: void
  status: 200
}

export type postUsuariosLoginResponseSuccess = (postUsuariosLoginResponse200) & {
  headers: Headers;
};
;

export type postUsuariosLoginResponse = (postUsuariosLoginResponseSuccess)

export const getPostUsuariosLoginUrl = () => {




  return `/usuarios/login`
}

export const postUsuariosLogin = async (postUsuariosLoginBody: PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree, options?: RequestInit): Promise<postUsuariosLoginResponse> => {

  return apiClient<postUsuariosLoginResponse>(getPostUsuariosLoginUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      postUsuariosLoginBody,)
  }
);}




export const getPostUsuariosLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsuariosLogin>>, TError,{data: PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postUsuariosLogin>>, TError,{data: PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree}, TContext> => {

const mutationKey = ['postUsuariosLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsuariosLogin>>, {data: PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  postUsuariosLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsuariosLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postUsuariosLogin>>>
    export type PostUsuariosLoginMutationBody = PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree
    export type PostUsuariosLoginMutationError = unknown

    export const usePostUsuariosLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsuariosLogin>>, TError,{data: PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsuariosLogin>>,
        TError,
        {data: PostUsuariosLoginBodyOne | PostUsuariosLoginBodyTwo | PostUsuariosLoginBodyThree},
        TContext
      > => {
      return useMutation(getPostUsuariosLoginMutationOptions(options), queryClient);
    }

export type postUsuariosLogoutResponse200 = {
  data: void
  status: 200
}

export type postUsuariosLogoutResponseSuccess = (postUsuariosLogoutResponse200) & {
  headers: Headers;
};
;

export type postUsuariosLogoutResponse = (postUsuariosLogoutResponseSuccess)

export const getPostUsuariosLogoutUrl = () => {




  return `/usuarios/logout`
}

export const postUsuariosLogout = async ( options?: RequestInit): Promise<postUsuariosLogoutResponse> => {

  return apiClient<postUsuariosLogoutResponse>(getPostUsuariosLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostUsuariosLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsuariosLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postUsuariosLogout>>, TError,void, TContext> => {

const mutationKey = ['postUsuariosLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsuariosLogout>>, void> = () => {


          return  postUsuariosLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsuariosLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postUsuariosLogout>>>

    export type PostUsuariosLogoutMutationError = unknown

    export const usePostUsuariosLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsuariosLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsuariosLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostUsuariosLogoutMutationOptions(options), queryClient);
    }

export type getUsuariosResponse200 = {
  data: void
  status: 200
}

export type getUsuariosResponseSuccess = (getUsuariosResponse200) & {
  headers: Headers;
};
;

export type getUsuariosResponse = (getUsuariosResponseSuccess)

export const getGetUsuariosUrl = (params?: GetUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/usuarios/?${stringifiedParams}` : `/usuarios/`
}

export const getUsuarios = async (params?: GetUsuariosParams, options?: RequestInit): Promise<getUsuariosResponse> => {

  return apiClient<getUsuariosResponse>(getGetUsuariosUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsuariosQueryKey = (params?: GetUsuariosParams,) => {
    return [
    `/usuarios/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUsuariosQueryOptions = <TData = Awaited<ReturnType<typeof getUsuarios>>, TError = unknown>(params?: GetUsuariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuarios>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsuariosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsuarios>>> = ({ signal }) => getUsuarios(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsuarios>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsuariosQueryResult = NonNullable<Awaited<ReturnType<typeof getUsuarios>>>
export type GetUsuariosQueryError = unknown


export function useGetUsuarios<TData = Awaited<ReturnType<typeof getUsuarios>>, TError = unknown>(
 params: undefined |  GetUsuariosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuarios>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsuarios>>,
          TError,
          Awaited<ReturnType<typeof getUsuarios>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsuarios<TData = Awaited<ReturnType<typeof getUsuarios>>, TError = unknown>(
 params?: GetUsuariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuarios>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsuarios>>,
          TError,
          Awaited<ReturnType<typeof getUsuarios>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsuarios<TData = Awaited<ReturnType<typeof getUsuarios>>, TError = unknown>(
 params?: GetUsuariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuarios>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsuarios<TData = Awaited<ReturnType<typeof getUsuarios>>, TError = unknown>(
 params?: GetUsuariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuarios>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsuariosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postUsuariosResponse200 = {
  data: void
  status: 200
}

export type postUsuariosResponseSuccess = (postUsuariosResponse200) & {
  headers: Headers;
};
;

export type postUsuariosResponse = (postUsuariosResponseSuccess)

export const getPostUsuariosUrl = () => {




  return `/usuarios/`
}

export const postUsuarios = async (postUsuariosBody: PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree, options?: RequestInit): Promise<postUsuariosResponse> => {

  return apiClient<postUsuariosResponse>(getPostUsuariosUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      postUsuariosBody,)
  }
);}




export const getPostUsuariosMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsuarios>>, TError,{data: PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postUsuarios>>, TError,{data: PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree}, TContext> => {

const mutationKey = ['postUsuarios'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsuarios>>, {data: PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  postUsuarios(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsuariosMutationResult = NonNullable<Awaited<ReturnType<typeof postUsuarios>>>
    export type PostUsuariosMutationBody = PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree
    export type PostUsuariosMutationError = unknown

    export const usePostUsuarios = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsuarios>>, TError,{data: PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsuarios>>,
        TError,
        {data: PostUsuariosBodyOne | PostUsuariosBodyTwo | PostUsuariosBodyThree},
        TContext
      > => {
      return useMutation(getPostUsuariosMutationOptions(options), queryClient);
    }

export type getUsuariosByIdResponse200 = {
  data: void
  status: 200
}

export type getUsuariosByIdResponseSuccess = (getUsuariosByIdResponse200) & {
  headers: Headers;
};
;

export type getUsuariosByIdResponse = (getUsuariosByIdResponseSuccess)

export const getGetUsuariosByIdUrl = (id: string,) => {




  return `/usuarios/${id}`
}

export const getUsuariosById = async (id: string, options?: RequestInit): Promise<getUsuariosByIdResponse> => {

  return apiClient<getUsuariosByIdResponse>(getGetUsuariosByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsuariosByIdQueryKey = (id: string,) => {
    return [
    `/usuarios/${id}`
    ] as const;
    }


export const getGetUsuariosByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUsuariosById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuariosById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsuariosByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsuariosById>>> = ({ signal }) => getUsuariosById(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsuariosById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsuariosByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUsuariosById>>>
export type GetUsuariosByIdQueryError = unknown


export function useGetUsuariosById<TData = Awaited<ReturnType<typeof getUsuariosById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuariosById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsuariosById>>,
          TError,
          Awaited<ReturnType<typeof getUsuariosById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsuariosById<TData = Awaited<ReturnType<typeof getUsuariosById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuariosById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsuariosById>>,
          TError,
          Awaited<ReturnType<typeof getUsuariosById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsuariosById<TData = Awaited<ReturnType<typeof getUsuariosById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuariosById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsuariosById<TData = Awaited<ReturnType<typeof getUsuariosById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsuariosById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsuariosByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type patchUsuariosByIdResponse200 = {
  data: void
  status: 200
}

export type patchUsuariosByIdResponseSuccess = (patchUsuariosByIdResponse200) & {
  headers: Headers;
};
;

export type patchUsuariosByIdResponse = (patchUsuariosByIdResponseSuccess)

export const getPatchUsuariosByIdUrl = (id: string,) => {




  return `/usuarios/${id}`
}

export const patchUsuariosById = async (id: string,
    patchUsuariosByIdBody: PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree, options?: RequestInit): Promise<patchUsuariosByIdResponse> => {

  return apiClient<patchUsuariosByIdResponse>(getPatchUsuariosByIdUrl(id),
  {
    ...options,
    method: 'PATCH'
    ,
    body: JSON.stringify(
      patchUsuariosByIdBody,)
  }
);}




export const getPatchUsuariosByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsuariosById>>, TError,{id: string;data: PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchUsuariosById>>, TError,{id: string;data: PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree}, TContext> => {

const mutationKey = ['patchUsuariosById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUsuariosById>>, {id: string;data: PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree}> = (props) => {
          const {id,data} = props ?? {};

          return  patchUsuariosById(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchUsuariosByIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchUsuariosById>>>
    export type PatchUsuariosByIdMutationBody = PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree
    export type PatchUsuariosByIdMutationError = unknown

    export const usePatchUsuariosById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsuariosById>>, TError,{id: string;data: PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUsuariosById>>,
        TError,
        {id: string;data: PatchUsuariosByIdBodyOne | PatchUsuariosByIdBodyTwo | PatchUsuariosByIdBodyThree},
        TContext
      > => {
      return useMutation(getPatchUsuariosByIdMutationOptions(options), queryClient);
    }

export type deleteUsuariosByIdResponse200 = {
  data: void
  status: 200
}

export type deleteUsuariosByIdResponseSuccess = (deleteUsuariosByIdResponse200) & {
  headers: Headers;
};
;

export type deleteUsuariosByIdResponse = (deleteUsuariosByIdResponseSuccess)

export const getDeleteUsuariosByIdUrl = (id: string,) => {




  return `/usuarios/${id}`
}

export const deleteUsuariosById = async (id: string, options?: RequestInit): Promise<deleteUsuariosByIdResponse> => {

  return apiClient<deleteUsuariosByIdResponse>(getDeleteUsuariosByIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUsuariosByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsuariosById>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsuariosById>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUsuariosById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsuariosById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUsuariosById(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsuariosByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsuariosById>>>

    export type DeleteUsuariosByIdMutationError = unknown

    export const useDeleteUsuariosById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsuariosById>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsuariosById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteUsuariosByIdMutationOptions(options), queryClient);
    }
